/**
 * 内置 NES / Famicom 标题库。
 *
 * 使用方式：只在导入流程里通过动态 import 加载，不进首屏包。
 *
 * 数据原则：
 * 1. `crcs` 一律留空。真实 CRC32 是实测数据，凭空编造会造成错误的「精确匹配」，
 *    危害远大于收益。精确匹配靠用户纠正后的本地自学习（crcLearn 表）逐步积累。
 * 2. 准确性优先于数量。年份 / 开发商 / 发行商拿不准的一律 null，不猜。
 * 3. year 取首发年份（多数是日本 Famicom 首发，少数只在北美发行的取 NES 年份）。
 * 4. players 表示该作最多支持几名玩家（含轮流制）。
 * 5. cn 只填中文圈确有共识的通行译名；民间叫法不统一的留 null，
 *    避免搜索时被错误译名污染。
 */
import type { TitleEntry } from '@/types/game'

export const NES_TITLES: readonly TitleEntry[] = [
  /* ------------------------------ 任天堂第一方 ----------------------------- */
  { id: 'super-mario-bros', title: 'Super Mario Bros.', aliases: ['SMB', 'Super Mario Brothers', 'Mario 1', '超级玛丽'], cn: '超级马里奥兄弟', year: 1985, categories: ['platformer'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'super-mario-bros-2-jp', title: 'Super Mario Bros. 2 (Japan)', aliases: ['The Lost Levels', 'Super Mario Bros. The Lost Levels', 'SMB2J'], cn: '超级马里奥兄弟2（日版）', year: 1986, categories: ['platformer'], developer: 'Nintendo', publisher: 'Nintendo', players: 1 },
  { id: 'super-mario-bros-2', title: 'Super Mario Bros. 2', aliases: ['SMB2', 'Doki Doki Panic', 'Super Mario USA'], cn: '超级马里奥兄弟2（美版）', year: 1988, categories: ['platformer'], developer: 'Nintendo', publisher: 'Nintendo', players: 1 },
  { id: 'super-mario-bros-3', title: 'Super Mario Bros. 3', aliases: ['SMB3', 'Mario 3'], cn: '超级马里奥兄弟3', year: 1988, categories: ['platformer'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'legend-of-zelda', title: 'The Legend of Zelda', aliases: ['Zelda no Densetsu', 'Zelda 1', 'Zelda'], cn: '塞尔达传说', year: 1986, categories: ['adventure', 'action'], developer: 'Nintendo', publisher: 'Nintendo', players: 1 },
  { id: 'zelda-2', title: 'Zelda II: The Adventure of Link', aliases: ['Adventure of Link', 'Link no Bouken', 'Zelda 2'], cn: '塞尔达传说2：林克的冒险', year: 1987, categories: ['action', 'rpg'], developer: 'Nintendo', publisher: 'Nintendo', players: 1 },
  { id: 'metroid', title: 'Metroid', aliases: ['Metroido'], cn: '银河战士', year: 1986, categories: ['action', 'adventure'], developer: 'Nintendo', publisher: 'Nintendo', players: 1 },
  { id: 'kid-icarus', title: 'Kid Icarus', aliases: ['Hikari Shinwa: Palutena no Kagami'], cn: '光神话：帕尔提娜之镜', year: 1986, categories: ['platformer', 'action'], developer: 'Nintendo', publisher: 'Nintendo', players: 1 },
  { id: 'punch-out', title: "Mike Tyson's Punch-Out!!", aliases: ['Punch-Out', 'Punch Out'], cn: '拳王', year: 1987, categories: ['sports', 'fighting'], developer: 'Nintendo', publisher: 'Nintendo', players: 1 },
  { id: 'kirbys-adventure', title: "Kirby's Adventure", aliases: ['Hoshi no Kirby: Yume no Izumi no Monogatari', 'Kirby'], cn: '星之卡比：梦之泉物语', year: 1993, categories: ['platformer'], developer: 'HAL Laboratory', publisher: 'Nintendo', players: 1 },
  { id: 'ice-climber', title: 'Ice Climber', aliases: ['Ice Climbers'], cn: '敲冰块', year: 1985, categories: ['platformer'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'balloon-fight', title: 'Balloon Fight', aliases: [], cn: '气球大战', year: 1985, categories: ['action'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'excitebike', title: 'Excitebike', aliases: ['Excite Bike'], cn: '越野摩托', year: 1984, categories: ['racing'], developer: 'Nintendo', publisher: 'Nintendo', players: 1 },
  { id: 'donkey-kong', title: 'Donkey Kong', aliases: ['DK'], cn: '大金刚', year: 1983, categories: ['platformer'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'donkey-kong-jr', title: 'Donkey Kong Jr.', aliases: ['Donkey Kong Junior'], cn: '大金刚Jr.', year: 1983, categories: ['platformer'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'donkey-kong-3', title: 'Donkey Kong 3', aliases: [], cn: '大金刚3', year: 1984, categories: ['shooter'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'mario-bros', title: 'Mario Bros.', aliases: ['Mario Brothers'], cn: '马里奥兄弟', year: 1983, categories: ['platformer'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'dr-mario', title: 'Dr. Mario', aliases: ['Doctor Mario'], cn: '马里奥医生', year: 1990, categories: ['puzzle'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'duck-hunt', title: 'Duck Hunt', aliases: [], cn: '打鸭子', year: 1984, categories: ['shooter'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'wild-gunman', title: 'Wild Gunman', aliases: [], cn: '西部枪手', year: 1984, categories: ['shooter'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'hogans-alley', title: "Hogan's Alley", aliases: [], cn: null, year: 1984, categories: ['shooter'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'golf', title: 'Golf', aliases: [], cn: '高尔夫', year: 1984, categories: ['sports'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'tennis', title: 'Tennis', aliases: [], cn: '网球', year: 1984, categories: ['sports'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'baseball', title: 'Baseball', aliases: [], cn: '棒球', year: 1983, categories: ['sports'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'pinball', title: 'Pinball', aliases: [], cn: '弹珠台', year: 1984, categories: ['action'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'clu-clu-land', title: 'Clu Clu Land', aliases: [], cn: null, year: 1984, categories: ['action', 'puzzle'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'devil-world', title: 'Devil World', aliases: [], cn: '恶魔世界', year: 1984, categories: ['action'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'urban-champion', title: 'Urban Champion', aliases: [], cn: '城市冠军', year: 1984, categories: ['fighting'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'wrecking-crew', title: 'Wrecking Crew', aliases: [], cn: '拆房子', year: 1985, categories: ['puzzle', 'platformer'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'mach-rider', title: 'Mach Rider', aliases: [], cn: null, year: 1985, categories: ['racing', 'shooter'], developer: 'Nintendo', publisher: 'Nintendo', players: 1 },
  { id: 'ice-hockey', title: 'Ice Hockey', aliases: [], cn: '冰球', year: 1988, categories: ['sports'], developer: null, publisher: 'Nintendo', players: 2 },
  { id: 'f1-race', title: 'F-1 Race', aliases: ['F1 Race'], cn: 'F1赛车', year: 1984, categories: ['racing'], developer: null, publisher: 'Nintendo', players: 2 },
  { id: 'gyromite', title: 'Gyromite', aliases: [], cn: null, year: 1985, categories: ['puzzle'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'stack-up', title: 'Stack-Up', aliases: [], cn: null, year: 1985, categories: ['puzzle'], developer: 'Nintendo', publisher: 'Nintendo', players: 1 },
  { id: 'popeye', title: 'Popeye', aliases: [], cn: '大力水手', year: 1983, categories: ['platformer'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'fire-emblem', title: 'Fire Emblem: Ankoku Ryu to Hikari no Tsurugi', aliases: ['Fire Emblem', 'Fire Emblem 1'], cn: '火焰纹章：暗黑龙与光之剑', year: 1990, categories: ['strategy', 'rpg'], developer: 'Intelligent Systems', publisher: 'Nintendo', players: 1 },
  { id: 'fire-emblem-gaiden', title: 'Fire Emblem Gaiden', aliases: [], cn: '火焰纹章外传', year: 1992, categories: ['strategy', 'rpg'], developer: 'Intelligent Systems', publisher: 'Nintendo', players: 1 },
  { id: 'famicom-wars', title: 'Famicom Wars', aliases: [], cn: '任天堂大战', year: 1988, categories: ['strategy'], developer: 'Intelligent Systems', publisher: 'Nintendo', players: 2 },
  { id: 'startropics', title: 'StarTropics', aliases: ['Star Tropics'], cn: null, year: 1990, categories: ['adventure', 'action'], developer: 'Nintendo', publisher: 'Nintendo', players: 1 },
  { id: 'yoshi', title: 'Yoshi', aliases: ['Mario & Yoshi', 'Yoshi no Tamago'], cn: '耀西的蛋', year: 1991, categories: ['puzzle'], developer: null, publisher: 'Nintendo', players: 2 },
  { id: 'yoshis-cookie', title: "Yoshi's Cookie", aliases: [], cn: '耀西饼干', year: 1992, categories: ['puzzle'], developer: null, publisher: 'Nintendo', players: 2 },
  { id: 'warios-woods', title: "Wario's Woods", aliases: [], cn: '瓦里奥的森林', year: 1994, categories: ['puzzle'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'tetris-nintendo', title: 'Tetris', aliases: ['Tetoris'], cn: '俄罗斯方块', year: 1989, categories: ['puzzle'], developer: null, publisher: 'Nintendo', players: 1 },
  { id: 'mother', title: 'Mother', aliases: ['EarthBound Beginnings', 'EarthBound Zero'], cn: '地球冒险', year: 1989, categories: ['rpg'], developer: 'Ape', publisher: 'Nintendo', players: 1 },
  { id: 'kung-fu', title: 'Kung Fu', aliases: ['Spartan X', 'Kung-Fu Master'], cn: '成龙踢馆', year: 1985, categories: ['action'], developer: 'Irem', publisher: 'Nintendo', players: 1 },
  { id: 'nintendo-world-cup', title: 'Nintendo World Cup', aliases: ['Nekketsu Koukou Dodgeball-bu: Soccer Hen'], cn: '热血足球', year: 1990, categories: ['sports'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 4 },

  /* -------------------------------- Konami -------------------------------- */
  { id: 'contra', title: 'Contra', aliases: ['Probotector', 'Gryzor'], cn: '魂斗罗', year: 1988, categories: ['shooter', 'action'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'super-c', title: 'Super C', aliases: ['Super Contra', 'Super Probotector'], cn: '超级魂斗罗', year: 1990, categories: ['shooter', 'action'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'contra-force', title: 'Contra Force', aliases: [], cn: '魂斗罗力量', year: 1992, categories: ['shooter', 'action'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'castlevania', title: 'Castlevania', aliases: ['Akumajou Dracula', 'Vampire Killer'], cn: '恶魔城', year: 1986, categories: ['platformer', 'action'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'castlevania-2', title: "Castlevania II: Simon's Quest", aliases: ['Dracula II: Noroi no Fuuin'], cn: '恶魔城2：西蒙的追寻', year: 1987, categories: ['platformer', 'adventure'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'castlevania-3', title: "Castlevania III: Dracula's Curse", aliases: ['Akumajou Densetsu'], cn: '恶魔城传说', year: 1989, categories: ['platformer', 'action'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'gradius', title: 'Gradius', aliases: ['Nemesis'], cn: '宇宙巡航机', year: 1986, categories: ['shooter'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'gradius-2', title: 'Gradius II', aliases: ['Nemesis 2'], cn: '宇宙巡航机2', year: 1988, categories: ['shooter'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'life-force', title: 'Life Force', aliases: ['Salamander', 'Lifeforce'], cn: '沙罗曼蛇', year: 1988, categories: ['shooter'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'jackal', title: 'Jackal', aliases: ['Tokushu Butai Jackal', 'Final Command'], cn: '赤色要塞', year: 1988, categories: ['shooter', 'action'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'rushn-attack', title: "Rush'n Attack", aliases: ['Green Beret'], cn: '绿色兵团', year: 1987, categories: ['action'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'twinbee', title: 'TwinBee', aliases: ['Twin Bee'], cn: '兵蜂', year: 1986, categories: ['shooter'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'moero-twinbee', title: 'Moero TwinBee: Cinnamon Hakase o Sukue!', aliases: ['Stinger', 'Moero TwinBee'], cn: '兵蜂2', year: 1986, categories: ['shooter'], developer: 'Konami', publisher: 'Konami', players: 3 },
  { id: 'goonies-2', title: 'The Goonies II', aliases: ['Goonies 2'], cn: '七宝奇谋2', year: 1987, categories: ['action', 'adventure'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'tmnt', title: 'Teenage Mutant Ninja Turtles', aliases: ['TMNT', 'Gekikame Ninja Den'], cn: '忍者神龟', year: 1989, categories: ['action', 'platformer'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'tmnt-2', title: 'Teenage Mutant Ninja Turtles II: The Arcade Game', aliases: ['TMNT 2'], cn: '忍者神龟2', year: 1990, categories: ['action'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'tmnt-3', title: 'Teenage Mutant Ninja Turtles III: The Manhattan Project', aliases: ['TMNT 3'], cn: '忍者神龟3', year: 1991, categories: ['action'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'tiny-toon', title: 'Tiny Toon Adventures', aliases: [], cn: '淘气小兵兵', year: 1991, categories: ['platformer'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'bucky-ohare', title: "Bucky O'Hare", aliases: [], cn: null, year: 1992, categories: ['platformer', 'action'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'metal-gear', title: 'Metal Gear', aliases: [], cn: '合金装备', year: 1987, categories: ['action', 'adventure'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'snakes-revenge', title: "Snake's Revenge", aliases: ['Metal Gear 2'], cn: '合金装备：蛇的复仇', year: 1990, categories: ['action', 'adventure'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'blades-of-steel', title: 'Blades of Steel', aliases: ['Konamic Ice Hockey'], cn: '冰上曲棍球', year: 1988, categories: ['sports'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'double-dribble', title: 'Double Dribble', aliases: ['Exciting Basket'], cn: '篮球', year: 1987, categories: ['sports'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'track-and-field', title: 'Track & Field', aliases: ['Hyper Olympic', 'Track and Field'], cn: '田径运动会', year: 1987, categories: ['sports'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'yie-ar-kung-fu', title: 'Yie Ar Kung-Fu', aliases: ['Yie Ar Kung Fu'], cn: '中国功夫', year: 1985, categories: ['fighting'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'getsu-fuuma-den', title: 'Getsu Fuuma Den', aliases: ['Getsufuumaden'], cn: '月风魔传', year: 1987, categories: ['action', 'adventure'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'parodius', title: 'Parodius Da!', aliases: ['Parodius'], cn: '逗趣大作战', year: 1990, categories: ['shooter'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'crisis-force', title: 'Crisis Force', aliases: [], cn: null, year: 1991, categories: ['shooter'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'lagrange-point', title: 'Lagrange Point', aliases: [], cn: '拉格朗日点', year: 1991, categories: ['rpg'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'esper-dream', title: 'Esper Dream', aliases: [], cn: null, year: 1987, categories: ['rpg', 'action'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'wai-wai-world', title: 'Wai Wai World', aliases: ['Konami Wai Wai World'], cn: null, year: 1988, categories: ['platformer', 'action'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'ganbare-goemon', title: 'Ganbare Goemon! Karakuri Douchuu', aliases: ['Mystical Ninja', 'Goemon'], cn: '大盗五右卫门', year: 1986, categories: ['action', 'adventure'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'ganbare-goemon-2', title: 'Ganbare Goemon 2', aliases: ['Goemon 2'], cn: '大盗五右卫门2', year: 1989, categories: ['action', 'platformer'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'ganbare-goemon-gaiden', title: 'Ganbare Goemon Gaiden: Kieta Ougon Kiseru', aliases: ['Goemon Gaiden'], cn: '大盗五右卫门外传', year: 1990, categories: ['rpg'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'circus-charlie', title: 'Circus Charlie', aliases: [], cn: '马戏团', year: 1986, categories: ['action'], developer: 'Konami', publisher: null, players: 2 },
  { id: 'antarctic-adventure', title: 'Antarctic Adventure', aliases: ['Kekkyoku Nankyoku Daibouken'], cn: '南极大冒险', year: 1985, categories: ['action', 'racing'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'road-fighter', title: 'Road Fighter', aliases: [], cn: '公路赛车', year: 1985, categories: ['racing'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'top-gun', title: 'Top Gun', aliases: [], cn: '壮志凌云', year: 1987, categories: ['simulation', 'shooter'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'castlevania-fds', title: 'Vampire Killer', aliases: [], cn: null, year: 1986, categories: ['platformer', 'action'], developer: 'Konami', publisher: 'Konami', players: 1 },

  /* -------------------------------- Capcom -------------------------------- */
  { id: 'mega-man', title: 'Mega Man', aliases: ['Rockman', 'Megaman', 'Rockman 1'], cn: '洛克人', year: 1987, categories: ['platformer', 'action'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'mega-man-2', title: 'Mega Man 2', aliases: ['Rockman 2', 'Megaman 2'], cn: '洛克人2', year: 1988, categories: ['platformer', 'action'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'mega-man-3', title: 'Mega Man 3', aliases: ['Rockman 3'], cn: '洛克人3', year: 1990, categories: ['platformer', 'action'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'mega-man-4', title: 'Mega Man 4', aliases: ['Rockman 4'], cn: '洛克人4', year: 1991, categories: ['platformer', 'action'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'mega-man-5', title: 'Mega Man 5', aliases: ['Rockman 5'], cn: '洛克人5', year: 1992, categories: ['platformer', 'action'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'mega-man-6', title: 'Mega Man 6', aliases: ['Rockman 6'], cn: '洛克人6', year: 1993, categories: ['platformer', 'action'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'ghosts-n-goblins', title: "Ghosts 'n Goblins", aliases: ['Makaimura', 'Ghosts and Goblins'], cn: '魔界村', year: 1986, categories: ['platformer', 'action'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'bionic-commando', title: 'Bionic Commando', aliases: ['Hitler no Fukkatsu: Top Secret'], cn: null, year: 1988, categories: ['action', 'platformer'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'ducktales', title: 'DuckTales', aliases: ['Duck Tales'], cn: '唐老鸭', year: 1989, categories: ['platformer'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'ducktales-2', title: 'DuckTales 2', aliases: ['Duck Tales 2'], cn: '唐老鸭2', year: 1993, categories: ['platformer'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'chip-n-dale', title: "Chip 'n Dale Rescue Rangers", aliases: ['Chip and Dale', 'Rescue Rangers'], cn: '松鼠大战', year: 1990, categories: ['platformer', 'action'], developer: 'Capcom', publisher: 'Capcom', players: 2 },
  { id: 'chip-n-dale-2', title: "Chip 'n Dale Rescue Rangers 2", aliases: ['Chip and Dale 2'], cn: '松鼠大战2', year: 1993, categories: ['platformer', 'action'], developer: 'Capcom', publisher: 'Capcom', players: 2 },
  { id: 'darkwing-duck', title: 'Darkwing Duck', aliases: [], cn: '黑鸭侠', year: 1992, categories: ['platformer', 'action'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'talespin', title: 'TaleSpin', aliases: ['Tale Spin'], cn: null, year: 1991, categories: ['shooter'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'little-nemo', title: 'Little Nemo: The Dream Master', aliases: ['Pajama Hero Nemo'], cn: '小尼莫的梦境冒险', year: 1990, categories: ['platformer'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'mighty-final-fight', title: 'Mighty Final Fight', aliases: ['Final Fight'], cn: '快打旋风', year: 1993, categories: ['action'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'street-fighter-2010', title: 'Street Fighter 2010: The Final Fight', aliases: ['SF2010'], cn: null, year: 1990, categories: ['action', 'platformer'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: '1942', title: '1942', aliases: [], cn: '1942', year: 1985, categories: ['shooter'], developer: 'Capcom', publisher: 'Capcom', players: 2 },
  { id: '1943', title: '1943: The Battle of Midway', aliases: ['1943'], cn: '1943', year: 1988, categories: ['shooter'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'section-z', title: 'Section Z', aliases: [], cn: null, year: 1987, categories: ['shooter'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'trojan', title: 'Trojan', aliases: ['Tatakai no Banka'], cn: null, year: 1987, categories: ['action'], developer: 'Capcom', publisher: 'Capcom', players: 2 },
  { id: 'legendary-wings', title: 'Legendary Wings', aliases: ['Ares no Tsubasa'], cn: null, year: 1988, categories: ['shooter'], developer: 'Capcom', publisher: 'Capcom', players: 2 },
  { id: 'gun-smoke', title: 'Gun.Smoke', aliases: ['Gunsmoke'], cn: null, year: 1988, categories: ['shooter'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'strider', title: 'Strider', aliases: ['Strider Hiryu'], cn: '飞龙', year: 1989, categories: ['action', 'platformer'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'code-name-viper', title: 'Code Name: Viper', aliases: ['Codename Viper'], cn: null, year: 1990, categories: ['action'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'sweet-home', title: 'Sweet Home', aliases: [], cn: '甜蜜之家', year: 1989, categories: ['rpg', 'adventure'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'willow', title: 'Willow', aliases: [], cn: null, year: 1989, categories: ['rpg', 'action'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'destiny-of-an-emperor', title: 'Destiny of an Emperor', aliases: ['Tenchi wo Kurau'], cn: '吞食天地', year: 1989, categories: ['rpg'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'tenchi-wo-kurau-2', title: 'Tenchi wo Kurau II: Shokatsu Koumei Den', aliases: ['Destiny of an Emperor II'], cn: '吞食天地2：诸葛孔明传', year: 1991, categories: ['rpg'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'little-mermaid', title: 'The Little Mermaid', aliases: [], cn: '小美人鱼', year: 1991, categories: ['platformer'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'magic-kingdom', title: 'Adventures in the Magic Kingdom', aliases: [], cn: null, year: 1990, categories: ['platformer', 'adventure'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'mickey-mousecapade', title: 'Mickey Mousecapade', aliases: ['Mickey Mouse: Fushigi no Kuni no Daibouken'], cn: '米老鼠', year: 1987, categories: ['platformer'], developer: 'Hudson Soft', publisher: 'Capcom', players: 1 },

  /* ---------------------------- Technos（热血系列） --------------------------- */
  { id: 'double-dragon', title: 'Double Dragon', aliases: ['DD'], cn: '双截龙', year: 1988, categories: ['action', 'fighting'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 1 },
  { id: 'double-dragon-2', title: 'Double Dragon II: The Revenge', aliases: ['DD2'], cn: '双截龙2', year: 1989, categories: ['action', 'fighting'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 2 },
  { id: 'double-dragon-3', title: 'Double Dragon III: The Sacred Stones', aliases: ['DD3'], cn: '双截龙3', year: 1991, categories: ['action', 'fighting'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 2 },
  { id: 'river-city-ransom', title: 'River City Ransom', aliases: ['Downtown Nekketsu Monogatari', 'Street Gangs'], cn: '热血物语', year: 1989, categories: ['action', 'rpg'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 2 },
  { id: 'renegade', title: 'Renegade', aliases: ['Nekketsu Kouha Kunio-kun'], cn: '热血硬派', year: 1987, categories: ['action', 'fighting'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 2 },
  { id: 'super-dodge-ball', title: 'Super Dodge Ball', aliases: ['Nekketsu Koukou Dodgeball-bu'], cn: '热血躲避球', year: 1989, categories: ['sports'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 2 },
  { id: 'nekketsu-undoukai', title: 'Downtown Nekketsu Koushinkyoku: Soreyuke Daiundoukai', aliases: ['Nekketsu Koushinkyoku'], cn: '热血大运动会', year: 1990, categories: ['sports'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 4 },
  { id: 'nekketsu-kakutou-densetsu', title: 'Nekketsu Kakutou Densetsu', aliases: [], cn: '热血格斗传说', year: 1992, categories: ['fighting'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 4 },
  { id: 'bikkuri-nekketsu-shin-kiroku', title: 'Bikkuri Nekketsu Shin Kiroku! Harukanaru Kin Medal', aliases: ['Nekketsu Shin Kiroku'], cn: '热血新纪录', year: 1992, categories: ['sports'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 4 },
  { id: 'crash-n-the-boys', title: "Crash 'n the Boys: Street Challenge", aliases: ['Bikkuri Nekketsu Shin Kiroku'], cn: null, year: 1992, categories: ['sports'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 4 },

  /* ----------------------------- Square / Enix ---------------------------- */
  { id: 'final-fantasy', title: 'Final Fantasy', aliases: ['FF1', 'FF'], cn: '最终幻想', year: 1987, categories: ['rpg'], developer: 'Square', publisher: 'Square', players: 1 },
  { id: 'final-fantasy-2', title: 'Final Fantasy II', aliases: ['FF2'], cn: '最终幻想2', year: 1988, categories: ['rpg'], developer: 'Square', publisher: 'Square', players: 1 },
  { id: 'final-fantasy-3', title: 'Final Fantasy III', aliases: ['FF3'], cn: '最终幻想3', year: 1990, categories: ['rpg'], developer: 'Square', publisher: 'Square', players: 1 },
  { id: 'rad-racer', title: 'Rad Racer', aliases: ['Highway Star'], cn: null, year: 1987, categories: ['racing'], developer: 'Square', publisher: 'Square', players: 1 },
  { id: '3d-worldrunner', title: '3-D WorldRunner', aliases: ['Tobidase Daisakusen', 'The 3-D Battles of WorldRunner'], cn: null, year: 1987, categories: ['action'], developer: 'Square', publisher: 'Square', players: 1 },
  { id: 'kings-knight', title: "King's Knight", aliases: [], cn: null, year: 1986, categories: ['shooter', 'rpg'], developer: 'Square', publisher: 'Square', players: 1 },
  { id: 'hanjuku-hero', title: 'Hanjuku Hero', aliases: [], cn: null, year: 1988, categories: ['strategy', 'simulation'], developer: 'Square', publisher: 'Square', players: 1 },
  { id: 'dragon-quest', title: 'Dragon Quest', aliases: ['Dragon Warrior', 'DQ1'], cn: '勇者斗恶龙', year: 1986, categories: ['rpg'], developer: 'Chunsoft', publisher: 'Enix', players: 1 },
  { id: 'dragon-quest-2', title: 'Dragon Quest II', aliases: ['Dragon Warrior II', 'DQ2'], cn: '勇者斗恶龙2', year: 1987, categories: ['rpg'], developer: 'Chunsoft', publisher: 'Enix', players: 1 },
  { id: 'dragon-quest-3', title: 'Dragon Quest III', aliases: ['Dragon Warrior III', 'DQ3'], cn: '勇者斗恶龙3', year: 1988, categories: ['rpg'], developer: 'Chunsoft', publisher: 'Enix', players: 1 },
  { id: 'dragon-quest-4', title: 'Dragon Quest IV', aliases: ['Dragon Warrior IV', 'DQ4'], cn: '勇者斗恶龙4', year: 1990, categories: ['rpg'], developer: 'Chunsoft', publisher: 'Enix', players: 1 },

  /* --------------------------------- Namco -------------------------------- */
  { id: 'pac-man', title: 'Pac-Man', aliases: ['Pacman', 'Puck Man'], cn: '吃豆人', year: 1984, categories: ['action', 'puzzle'], developer: 'Namco', publisher: 'Namco', players: 2 },
  { id: 'galaxian', title: 'Galaxian', aliases: [], cn: '小蜜蜂', year: 1984, categories: ['shooter'], developer: 'Namco', publisher: 'Namco', players: 2 },
  { id: 'galaga', title: 'Galaga', aliases: ['Galaga: Demons of Death'], cn: '大蜜蜂', year: 1985, categories: ['shooter'], developer: 'Namco', publisher: 'Namco', players: 2 },
  { id: 'xevious', title: 'Xevious', aliases: [], cn: '铁板阵', year: 1984, categories: ['shooter'], developer: 'Namco', publisher: 'Namco', players: 2 },
  { id: 'mappy', title: 'Mappy', aliases: [], cn: '猫捉老鼠', year: 1984, categories: ['platformer'], developer: 'Namco', publisher: 'Namco', players: 2 },
  { id: 'dig-dug', title: 'Dig Dug', aliases: [], cn: null, year: 1985, categories: ['puzzle', 'action'], developer: 'Namco', publisher: 'Namco', players: 2 },
  { id: 'battle-city', title: 'Battle City', aliases: ['Tank 1990', 'Tank'], cn: '坦克大战', year: 1985, categories: ['shooter'], developer: 'Namco', publisher: 'Namco', players: 2 },
  { id: 'tower-of-druaga', title: 'The Tower of Druaga', aliases: ['Druaga no Tou'], cn: '迷宫塔', year: 1985, categories: ['action', 'rpg'], developer: 'Namco', publisher: 'Namco', players: 1 },
  { id: 'sky-kid', title: 'Sky Kid', aliases: [], cn: null, year: 1986, categories: ['shooter'], developer: 'Namco', publisher: 'Namco', players: 2 },
  { id: 'star-luster', title: 'Star Luster', aliases: [], cn: null, year: 1985, categories: ['simulation', 'shooter'], developer: 'Namco', publisher: 'Namco', players: 1 },
  { id: 'warpman', title: 'Warpman', aliases: [], cn: null, year: 1985, categories: ['action'], developer: 'Namco', publisher: 'Namco', players: 2 },
  { id: 'pac-land', title: 'Pac-Land', aliases: [], cn: null, year: 1985, categories: ['platformer'], developer: 'Namco', publisher: 'Namco', players: 1 },
  { id: 'dragon-buster', title: 'Dragon Buster', aliases: [], cn: null, year: 1987, categories: ['action', 'rpg'], developer: 'Namco', publisher: 'Namco', players: 1 },
  { id: 'rolling-thunder', title: 'Rolling Thunder', aliases: [], cn: null, year: 1989, categories: ['action'], developer: 'Namco', publisher: 'Namco', players: 1 },
  { id: 'splatterhouse-graffiti', title: 'Splatterhouse: Wanpaku Graffiti', aliases: ['Splatterhouse'], cn: 'splatterhouse 恶魔战士', year: 1989, categories: ['action', 'platformer'], developer: 'Namco', publisher: 'Namco', players: 1 },
  { id: 'youkai-douchuuki', title: 'Youkai Douchuuki', aliases: [], cn: '妖怪道中记', year: 1988, categories: ['platformer', 'action'], developer: 'Namco', publisher: 'Namco', players: 1 },
  { id: 'famista', title: 'Pro Yakyuu Family Stadium', aliases: ['Famista', 'Family Stadium'], cn: '棒球家族', year: 1986, categories: ['sports'], developer: 'Namco', publisher: 'Namco', players: 2 },
  { id: 'macross', title: 'Choujikuu Yousai Macross', aliases: ['Macross'], cn: '超时空要塞', year: 1985, categories: ['shooter'], developer: 'Namco', publisher: 'Namco', players: 1 },

  /* --------------------------------- Tecmo -------------------------------- */
  { id: 'ninja-gaiden', title: 'Ninja Gaiden', aliases: ['Ninja Ryukenden', 'Shadow Warriors'], cn: '忍者龙剑传', year: 1988, categories: ['action', 'platformer'], developer: 'Tecmo', publisher: 'Tecmo', players: 1 },
  { id: 'ninja-gaiden-2', title: 'Ninja Gaiden II: The Dark Sword of Chaos', aliases: ['Ninja Ryukenden II'], cn: '忍者龙剑传2', year: 1990, categories: ['action', 'platformer'], developer: 'Tecmo', publisher: 'Tecmo', players: 1 },
  { id: 'ninja-gaiden-3', title: 'Ninja Gaiden III: The Ancient Ship of Doom', aliases: ['Ninja Ryukenden III'], cn: '忍者龙剑传3', year: 1991, categories: ['action', 'platformer'], developer: 'Tecmo', publisher: 'Tecmo', players: 1 },
  { id: 'tecmo-bowl', title: 'Tecmo Bowl', aliases: [], cn: null, year: 1989, categories: ['sports'], developer: 'Tecmo', publisher: 'Tecmo', players: 2 },
  { id: 'tecmo-super-bowl', title: 'Tecmo Super Bowl', aliases: [], cn: null, year: 1991, categories: ['sports'], developer: 'Tecmo', publisher: 'Tecmo', players: 2 },
  { id: 'solomons-key', title: "Solomon's Key", aliases: ['Solomon no Kagi'], cn: '所罗门之钥', year: 1986, categories: ['puzzle', 'platformer'], developer: 'Tecmo', publisher: 'Tecmo', players: 2 },
  { id: 'rygar', title: 'Rygar', aliases: ['Argos no Senshi'], cn: '阿古斯战士', year: 1987, categories: ['action', 'adventure'], developer: 'Tecmo', publisher: 'Tecmo', players: 1 },
  { id: 'captain-tsubasa', title: 'Captain Tsubasa', aliases: ['Tsubasa'], cn: '足球小将', year: 1988, categories: ['sports', 'rpg'], developer: 'Tecmo', publisher: 'Tecmo', players: 1 },
  { id: 'captain-tsubasa-2', title: 'Captain Tsubasa Vol. II: Super Striker', aliases: ['Captain Tsubasa 2'], cn: '足球小将2', year: 1990, categories: ['sports', 'rpg'], developer: 'Tecmo', publisher: 'Tecmo', players: 1 },
  { id: 'mighty-bomb-jack', title: 'Mighty Bomb Jack', aliases: ['Bomb Jack'], cn: '炸弹杰克', year: 1986, categories: ['platformer'], developer: 'Tecmo', publisher: 'Tecmo', players: 1 },
  { id: 'silkworm', title: 'Silkworm', aliases: [], cn: null, year: 1990, categories: ['shooter'], developer: 'Tecmo', publisher: null, players: 2 },

  /* ------------------------------ Hudson Soft ----------------------------- */
  { id: 'adventure-island', title: 'Adventure Island', aliases: ['Takahashi Meijin no Bouken Jima', 'Hudson Adventure Island'], cn: '高桥名人的冒险岛', year: 1986, categories: ['platformer'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 1 },
  { id: 'adventure-island-2', title: 'Adventure Island II', aliases: ['Takahashi Meijin no Bouken Jima II'], cn: '冒险岛2', year: 1991, categories: ['platformer'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 1 },
  { id: 'adventure-island-3', title: 'Adventure Island III', aliases: ['Takahashi Meijin no Bouken Jima III'], cn: '冒险岛3', year: 1992, categories: ['platformer'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 1 },
  { id: 'bomberman', title: 'Bomberman', aliases: ['Bomber Man'], cn: '炸弹人', year: 1985, categories: ['action', 'puzzle'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 1 },
  { id: 'bomberman-2', title: 'Bomberman II', aliases: ['Bomber Man II'], cn: '炸弹人2', year: 1991, categories: ['action', 'puzzle'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 3 },
  { id: 'lode-runner', title: 'Lode Runner', aliases: ['Loderunner'], cn: '淘金者', year: 1984, categories: ['puzzle', 'platformer'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 1 },
  { id: 'championship-lode-runner', title: 'Championship Lode Runner', aliases: [], cn: '淘金者：冠军版', year: 1985, categories: ['puzzle', 'platformer'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 1 },
  { id: 'nuts-and-milk', title: 'Nuts & Milk', aliases: ['Nuts and Milk'], cn: null, year: 1984, categories: ['puzzle', 'platformer'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 2 },
  { id: 'binary-land', title: 'Binary Land', aliases: [], cn: null, year: 1985, categories: ['puzzle'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 2 },
  { id: 'milons-secret-castle', title: "Milon's Secret Castle", aliases: ['Meikyuu Kumikyoku: Milon no Daibouken'], cn: '米隆的秘密城堡', year: 1986, categories: ['platformer', 'puzzle'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 1 },
  { id: 'star-soldier', title: 'Star Soldier', aliases: [], cn: '星际战士', year: 1986, categories: ['shooter'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 1 },
  { id: 'star-force', title: 'Star Force', aliases: [], cn: null, year: 1985, categories: ['shooter'], developer: 'Tehkan', publisher: 'Hudson Soft', players: 1 },
  { id: 'hector-87', title: "Hector '87", aliases: ['Starship Hector'], cn: null, year: 1987, categories: ['shooter'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 1 },
  { id: 'momotarou-densetsu', title: 'Momotarou Densetsu', aliases: ['Momotaro Densetsu'], cn: '桃太郎传说', year: 1987, categories: ['rpg'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 1 },
  { id: 'doraemon', title: 'Doraemon', aliases: [], cn: '哆啦A梦', year: 1986, categories: ['action', 'platformer'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 1 },
  { id: 'faxanadu', title: 'Faxanadu', aliases: [], cn: null, year: 1987, categories: ['action', 'rpg'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 1 },
  { id: 'felix-the-cat', title: 'Felix the Cat', aliases: [], cn: '菲力猫', year: 1992, categories: ['platformer'], developer: 'Hudson Soft', publisher: 'Hudson Soft', players: 1 },
  { id: 'jackie-chan', title: "Jackie Chan's Action Kung Fu", aliases: ['Jackie Chan'], cn: '成龙之龙', year: 1990, categories: ['platformer', 'action'], developer: null, publisher: 'Hudson Soft', players: 1 },

  /* ---------------------------------- Irem -------------------------------- */
  { id: 'spelunker', title: 'Spelunker', aliases: [], cn: '洞窟探险', year: 1985, categories: ['platformer'], developer: 'Irem', publisher: 'Irem', players: 1 },
  { id: 'kid-niki', title: 'Kid Niki: Radical Ninja', aliases: ['Kaiketsu Yanchamaru'], cn: null, year: 1987, categories: ['platformer', 'action'], developer: 'Irem', publisher: 'Irem', players: 1 },
  { id: 'zippy-race', title: 'Zippy Race', aliases: [], cn: null, year: 1985, categories: ['racing'], developer: 'Irem', publisher: 'Irem', players: 1 },
  { id: '10-yard-fight', title: '10-Yard Fight', aliases: [], cn: null, year: 1985, categories: ['sports'], developer: 'Irem', publisher: 'Irem', players: 2 },
  { id: 'image-fight', title: 'Image Fight', aliases: [], cn: null, year: 1990, categories: ['shooter'], developer: 'Irem', publisher: 'Irem', players: 1 },
  { id: 'holy-diver', title: 'Holy Diver', aliases: [], cn: null, year: 1989, categories: ['platformer', 'action'], developer: 'Irem', publisher: 'Irem', players: 1 },
  { id: 'metal-storm', title: 'Metal Storm', aliases: [], cn: null, year: 1991, categories: ['platformer', 'action'], developer: 'Irem', publisher: 'Irem', players: 1 },

  /* -------------------------------- SunSoft ------------------------------- */
  { id: 'batman', title: 'Batman: The Video Game', aliases: ['Batman'], cn: '蝙蝠侠', year: 1989, categories: ['platformer', 'action'], developer: 'Sunsoft', publisher: 'Sunsoft', players: 1 },
  { id: 'batman-return-of-the-joker', title: 'Batman: Return of the Joker', aliases: ['Dynamite Batman'], cn: '蝙蝠侠：小丑归来', year: 1991, categories: ['platformer', 'action'], developer: 'Sunsoft', publisher: 'Sunsoft', players: 1 },
  { id: 'blaster-master', title: 'Blaster Master', aliases: ['Chou Wakusei Senki Metafight', 'Metafight'], cn: '超惑星战记', year: 1988, categories: ['action', 'platformer'], developer: 'Sunsoft', publisher: 'Sunsoft', players: 1 },
  { id: 'journey-to-silius', title: 'Journey to Silius', aliases: ['Raf World'], cn: null, year: 1990, categories: ['platformer', 'shooter'], developer: 'Sunsoft', publisher: 'Sunsoft', players: 1 },
  { id: 'gremlins-2', title: 'Gremlins 2: The New Batch', aliases: ['Gremlins 2'], cn: '小精灵2', year: 1990, categories: ['action'], developer: 'Sunsoft', publisher: 'Sunsoft', players: 1 },
  { id: 'festers-quest', title: "Fester's Quest", aliases: [], cn: null, year: 1989, categories: ['action', 'adventure'], developer: 'Sunsoft', publisher: 'Sunsoft', players: 1 },
  { id: 'gimmick', title: 'Gimmick!', aliases: ['Mr. Gimmick'], cn: null, year: 1992, categories: ['platformer'], developer: 'Sunsoft', publisher: 'Sunsoft', players: 1 },
  { id: 'ufouria', title: 'Ufouria: The Saga', aliases: ['Hebereke'], cn: null, year: 1991, categories: ['platformer', 'adventure'], developer: 'Sunsoft', publisher: 'Sunsoft', players: 1 },
  { id: 'platoon', title: 'Platoon', aliases: [], cn: '野战排', year: 1988, categories: ['action', 'shooter'], developer: null, publisher: 'Sunsoft', players: 1 },

  /* --------------------------------- Taito -------------------------------- */
  { id: 'bubble-bobble', title: 'Bubble Bobble', aliases: [], cn: '泡泡龙', year: 1987, categories: ['platformer', 'puzzle'], developer: 'Taito', publisher: 'Taito', players: 2 },
  { id: 'bubble-bobble-2', title: 'Bubble Bobble Part 2', aliases: [], cn: '泡泡龙2', year: 1993, categories: ['platformer', 'puzzle'], developer: 'Taito', publisher: 'Taito', players: 1 },
  { id: 'arkanoid', title: 'Arkanoid', aliases: [], cn: '打砖块', year: 1986, categories: ['puzzle', 'action'], developer: 'Taito', publisher: 'Taito', players: 2 },
  { id: 'elevator-action', title: 'Elevator Action', aliases: [], cn: '电梯大战', year: 1985, categories: ['action'], developer: 'Taito', publisher: 'Taito', players: 2 },
  { id: 'legend-of-kage', title: 'The Legend of Kage', aliases: ['Kage no Densetsu'], cn: '影子传说', year: 1986, categories: ['action', 'platformer'], developer: 'Taito', publisher: 'Taito', players: 2 },
  { id: 'rainbow-islands', title: 'Rainbow Islands: The Story of Bubble Bobble 2', aliases: ['Rainbow Islands'], cn: '彩虹岛', year: 1991, categories: ['platformer'], developer: 'Taito', publisher: 'Taito', players: 1 },
  { id: 'operation-wolf', title: 'Operation Wolf', aliases: [], cn: null, year: 1989, categories: ['shooter'], developer: 'Taito', publisher: 'Taito', players: 1 },
  { id: 'insector-x', title: 'Insector X', aliases: [], cn: null, year: 1990, categories: ['shooter'], developer: null, publisher: 'Taito', players: 1 },
  { id: 'takeshi-no-chousenjou', title: 'Takeshi no Chousenjou', aliases: [], cn: '北野武的挑战状', year: 1986, categories: ['adventure'], developer: null, publisher: 'Taito', players: 1 },
  { id: 'little-samson', title: 'Little Samson', aliases: ['Seirei Densetsu Lickle'], cn: null, year: 1992, categories: ['platformer'], developer: 'Takeru', publisher: 'Taito', players: 1 },
  { id: 'power-blade', title: 'Power Blade', aliases: ['Power Blazer'], cn: null, year: 1991, categories: ['action', 'platformer'], developer: 'Natsume', publisher: 'Taito', players: 1 },
  { id: 'kick-master', title: 'Kick Master', aliases: [], cn: null, year: 1992, categories: ['action', 'platformer'], developer: null, publisher: 'Taito', players: 1 },
  { id: 'wrath-of-the-black-manta', title: 'Wrath of the Black Manta', aliases: ['Ninja Cop Saizou'], cn: null, year: 1990, categories: ['action'], developer: null, publisher: 'Taito', players: 1 },
  { id: 'flintstones-dino', title: 'The Flintstones: The Rescue of Dino & Hoppy', aliases: ['Flintstones'], cn: '摩登原始人', year: 1991, categories: ['platformer'], developer: null, publisher: 'Taito', players: 1 },

  /* --------------------------------- Jaleco ------------------------------- */
  { id: 'city-connection', title: 'City Connection', aliases: [], cn: null, year: 1985, categories: ['platformer', 'action'], developer: 'Jaleco', publisher: 'Jaleco', players: 2 },
  { id: 'exerion', title: 'Exerion', aliases: [], cn: null, year: 1985, categories: ['shooter'], developer: 'Jaleco', publisher: 'Jaleco', players: 2 },
  { id: 'field-combat', title: 'Field Combat', aliases: [], cn: null, year: 1985, categories: ['shooter'], developer: 'Jaleco', publisher: 'Jaleco', players: 1 },
  { id: 'ninja-jajamaru-kun', title: 'Ninja JaJaMaru-kun', aliases: ['Jajamaru'], cn: null, year: 1985, categories: ['platformer', 'action'], developer: 'Jaleco', publisher: 'Jaleco', players: 2 },
  { id: 'bases-loaded', title: 'Bases Loaded', aliases: ['Moero!! Pro Yakyuu'], cn: null, year: 1987, categories: ['sports'], developer: 'Jaleco', publisher: 'Jaleco', players: 2 },
  { id: 'astyanax', title: 'Astyanax', aliases: ['The Lord of King'], cn: null, year: 1990, categories: ['action', 'platformer'], developer: 'Jaleco', publisher: 'Jaleco', players: 1 },
  { id: 'maniac-mansion', title: 'Maniac Mansion', aliases: [], cn: null, year: 1990, categories: ['adventure'], developer: 'Lucasfilm Games', publisher: 'Jaleco', players: 1 },

  /* ---------------------------------- SNK --------------------------------- */
  { id: 'ikari-warriors', title: 'Ikari Warriors', aliases: ['Ikari'], cn: '怒', year: 1986, categories: ['shooter', 'action'], developer: 'SNK', publisher: 'SNK', players: 2 },
  { id: 'ikari-warriors-2', title: 'Ikari Warriors II: Victory Road', aliases: ['Victory Road'], cn: '怒2', year: 1988, categories: ['shooter', 'action'], developer: 'SNK', publisher: 'SNK', players: 2 },
  { id: 'athena', title: 'Athena', aliases: [], cn: '雅典娜', year: 1987, categories: ['platformer', 'action'], developer: 'SNK', publisher: 'SNK', players: 1 },
  { id: 'guerrilla-war', title: 'Guerrilla War', aliases: ['Guevara'], cn: null, year: 1989, categories: ['shooter', 'action'], developer: 'SNK', publisher: 'SNK', players: 2 },
  { id: 'pow', title: 'P.O.W.: Prisoners of War', aliases: ['POW'], cn: null, year: 1989, categories: ['action'], developer: 'SNK', publisher: 'SNK', players: 2 },
  { id: 'crystalis', title: 'Crystalis', aliases: ['God Slayer'], cn: null, year: 1990, categories: ['rpg', 'action'], developer: 'SNK', publisher: 'SNK', players: 1 },
  { id: 'baseball-stars', title: 'Baseball Stars', aliases: [], cn: null, year: 1989, categories: ['sports'], developer: 'SNK', publisher: 'SNK', players: 2 },

  /* ------------------------------ Rare / 欧美 ------------------------------ */
  { id: 'battletoads', title: 'Battletoads', aliases: [], cn: '忍者蛙', year: 1991, categories: ['action', 'platformer'], developer: 'Rare', publisher: 'Tradewest', players: 2 },
  { id: 'battletoads-double-dragon', title: 'Battletoads & Double Dragon', aliases: ['Battletoads and Double Dragon'], cn: '忍者蛙与双截龙', year: 1993, categories: ['action'], developer: 'Rare', publisher: 'Tradewest', players: 2 },
  { id: 'rc-pro-am', title: 'R.C. Pro-Am', aliases: ['RC Pro Am'], cn: null, year: 1988, categories: ['racing'], developer: 'Rare', publisher: 'Nintendo', players: 1 },
  { id: 'snake-rattle-n-roll', title: "Snake Rattle 'n' Roll", aliases: [], cn: null, year: 1990, categories: ['action', 'platformer'], developer: 'Rare', publisher: 'Nintendo', players: 2 },
  { id: 'wizards-and-warriors', title: 'Wizards & Warriors', aliases: ['Wizards and Warriors'], cn: null, year: 1987, categories: ['platformer', 'action'], developer: 'Rare', publisher: 'Acclaim', players: 1 },
  { id: 'cobra-triangle', title: 'Cobra Triangle', aliases: [], cn: null, year: 1989, categories: ['racing', 'action'], developer: 'Rare', publisher: 'Nintendo', players: 1 },
  { id: 'solar-jetman', title: 'Solar Jetman: Hunt for the Golden Warpship', aliases: ['Solar Jetman'], cn: null, year: 1990, categories: ['action'], developer: 'Rare', publisher: null, players: 1 },
  { id: 'marble-madness', title: 'Marble Madness', aliases: [], cn: null, year: 1989, categories: ['puzzle', 'action'], developer: 'Rare', publisher: 'Milton Bradley', players: 2 },

  /* ------------------------------- Data East ------------------------------ */
  { id: 'burgertime', title: 'BurgerTime', aliases: ['Burger Time'], cn: '汉堡时代', year: 1985, categories: ['action'], developer: 'Data East', publisher: 'Data East', players: 2 },
  { id: 'karate-champ', title: 'Karate Champ', aliases: ['Karate Do'], cn: '空手道', year: 1986, categories: ['fighting'], developer: 'Data East', publisher: 'Data East', players: 2 },
  { id: 'bad-dudes', title: 'Bad Dudes vs. DragonNinja', aliases: ['Bad Dudes', 'DragonNinja'], cn: null, year: 1990, categories: ['action'], developer: 'Data East', publisher: 'Data East', players: 2 },
  { id: 'heavy-barrel', title: 'Heavy Barrel', aliases: [], cn: null, year: 1990, categories: ['shooter', 'action'], developer: 'Data East', publisher: 'Data East', players: 2 },
  { id: 'robocop', title: 'RoboCop', aliases: [], cn: '机械战警', year: 1989, categories: ['action', 'platformer'], developer: 'Data East', publisher: 'Data East', players: 1 },
  { id: 'robocop-2', title: 'RoboCop 2', aliases: [], cn: '机械战警2', year: 1991, categories: ['action', 'platformer'], developer: 'Data East', publisher: 'Data East', players: 1 },
  { id: 'tag-team-wrestling', title: 'Tag Team Wrestling', aliases: [], cn: '双人摔跤', year: 1986, categories: ['sports', 'fighting'], developer: 'Data East', publisher: 'Data East', players: 2 },
  { id: 'rampage', title: 'Rampage', aliases: [], cn: '怪兽大破坏', year: 1988, categories: ['action'], developer: null, publisher: 'Data East', players: 2 },

  /* ------------------------------- HAL / 益智 ------------------------------ */
  { id: 'adventures-of-lolo', title: 'Adventures of Lolo', aliases: ['Eggerland'], cn: '洛洛的冒险', year: 1989, categories: ['puzzle'], developer: 'HAL Laboratory', publisher: 'HAL Laboratory', players: 1 },
  { id: 'adventures-of-lolo-2', title: 'Adventures of Lolo 2', aliases: [], cn: '洛洛的冒险2', year: 1990, categories: ['puzzle'], developer: 'HAL Laboratory', publisher: 'HAL Laboratory', players: 1 },
  { id: 'adventures-of-lolo-3', title: 'Adventures of Lolo 3', aliases: [], cn: '洛洛的冒险3', year: 1991, categories: ['puzzle'], developer: 'HAL Laboratory', publisher: 'HAL Laboratory', players: 1 },

  /* -------------------------------- Natsume ------------------------------- */
  { id: 'shadow-of-the-ninja', title: 'Shadow of the Ninja', aliases: ['Kage', 'Blue Shadow'], cn: null, year: 1990, categories: ['action', 'platformer'], developer: 'Natsume', publisher: 'Natsume', players: 2 },
  { id: 'scat', title: 'S.C.A.T.: Special Cybernetic Attack Team', aliases: ['SCAT', 'Final Mission'], cn: null, year: 1991, categories: ['shooter'], developer: 'Natsume', publisher: 'Natsume', players: 2 },
  { id: 'abadox', title: 'Abadox: The Deadly Inner War', aliases: ['Abadox'], cn: null, year: 1990, categories: ['shooter'], developer: 'Natsume', publisher: null, players: 1 },
  { id: 'mitsume-ga-tooru', title: 'Mitsume ga Tooru', aliases: ['The Three-Eyed One'], cn: '三眼神童', year: 1992, categories: ['action', 'platformer'], developer: 'Natsume', publisher: 'Natsume', players: 1 },

  /* -------------------------------- Compile ------------------------------- */
  { id: 'zanac', title: 'Zanac', aliases: [], cn: null, year: 1986, categories: ['shooter'], developer: 'Compile', publisher: 'Pony Canyon', players: 1 },
  { id: 'guardian-legend', title: 'The Guardian Legend', aliases: ['Guardic Gaiden'], cn: '守护者传说', year: 1988, categories: ['shooter', 'adventure'], developer: 'Compile', publisher: null, players: 1 },
  { id: 'gun-nac', title: 'Gun-Nac', aliases: ['GunNac'], cn: null, year: 1990, categories: ['shooter'], developer: 'Compile', publisher: null, players: 1 },

  /* ------------------------------- 万代 / 版权作 ---------------------------- */
  { id: 'kinnikuman', title: 'Kinnikuman: Muscle Tag Match', aliases: ['MUSCLE', 'Kinnikuman'], cn: '金肉人', year: 1985, categories: ['fighting'], developer: null, publisher: 'Bandai', players: 2 },
  { id: 'dragon-ball-shenlong', title: 'Dragon Ball: Shenlong no Nazo', aliases: ['Dragon Power', 'Dragon Ball'], cn: '龙珠：神龙之谜', year: 1986, categories: ['action', 'adventure'], developer: null, publisher: 'Bandai', players: 1 },
  { id: 'dragon-ball-z-kyoushuu', title: 'Dragon Ball Z: Kyoushuu! Saiyajin', aliases: ['Dragon Ball Z'], cn: '龙珠Z：强袭赛亚人', year: 1990, categories: ['rpg'], developer: null, publisher: 'Bandai', players: 1 },
  { id: 'saint-seiya-ougon', title: 'Saint Seiya: Ougon Densetsu', aliases: ['Saint Seiya'], cn: '圣斗士星矢：黄金传说', year: 1987, categories: ['rpg', 'action'], developer: null, publisher: 'Bandai', players: 1 },
  { id: 'saint-seiya-ougon-kanketsu', title: 'Saint Seiya: Ougon Densetsu Kanketsu Hen', aliases: ['Saint Seiya 2'], cn: '圣斗士星矢：黄金传说完结篇', year: 1988, categories: ['rpg', 'action'], developer: null, publisher: 'Bandai', players: 1 },
  { id: 'sd-gundam-gachapon-2', title: 'SD Gundam: Gachapon Senshi 2 - Capsule Senki', aliases: ['SD Gundam', 'Gachapon Senshi 2'], cn: 'SD高达：胶囊战记2', year: 1990, categories: ['strategy'], developer: null, publisher: 'Bandai', players: 2 },
  { id: 'hokuto-no-ken', title: 'Hokuto no Ken', aliases: ['Fist of the North Star'], cn: '北斗神拳', year: 1986, categories: ['action', 'fighting'], developer: null, publisher: 'Toei Animation', players: 1 },
  { id: 'star-wars-jvc', title: 'Star Wars', aliases: [], cn: '星球大战', year: 1991, categories: ['platformer', 'action'], developer: null, publisher: 'JVC', players: 1 },
  { id: 'simpsons-bart-space-mutants', title: 'The Simpsons: Bart vs. the Space Mutants', aliases: ['The Simpsons'], cn: '辛普森一家', year: 1991, categories: ['platformer'], developer: null, publisher: 'Acclaim', players: 1 },

  /* ------------------------------- Culture Brain --------------------------- */
  { id: 'kung-fu-heroes', title: 'Kung-Fu Heroes', aliases: ['Chinese Hero', 'Super Chinese'], cn: '中国英雄', year: 1989, categories: ['action'], developer: 'Culture Brain', publisher: 'Culture Brain', players: 2 },
  { id: 'little-ninja-brothers', title: 'Little Ninja Brothers', aliases: ['Super Chinese 2'], cn: '中国小子', year: 1990, categories: ['rpg', 'action'], developer: 'Culture Brain', publisher: 'Culture Brain', players: 2 },
  { id: 'flying-dragon', title: 'Flying Dragon: The Secret Scroll', aliases: ['Hiryu no Ken'], cn: '飞龙之拳', year: 1988, categories: ['fighting'], developer: 'Culture Brain', publisher: 'Culture Brain', players: 1 },
  { id: 'hiryu-no-ken-2', title: 'Hiryu no Ken II: Dragon no Tsubasa', aliases: ['Flying Dragon 2'], cn: '飞龙之拳2', year: 1988, categories: ['fighting'], developer: 'Culture Brain', publisher: 'Culture Brain', players: 2 },

  /* ---------------------------------- Koei -------------------------------- */
  { id: 'sangokushi', title: 'Sangokushi', aliases: ['Romance of the Three Kingdoms'], cn: '三国志', year: 1988, categories: ['strategy', 'simulation'], developer: 'Koei', publisher: 'Koei', players: 1 },
  { id: 'nobunagas-ambition', title: "Nobunaga's Ambition", aliases: ['Nobunaga no Yabou'], cn: '信长的野望', year: 1988, categories: ['strategy', 'simulation'], developer: 'Koei', publisher: 'Koei', players: 1 },
  { id: 'genghis-khan', title: 'Genghis Khan', aliases: ['Aoki Ookami to Shiroki Mejika'], cn: '成吉思汗', year: 1989, categories: ['strategy', 'simulation'], developer: 'Koei', publisher: 'Koei', players: 1 },
  { id: 'bandit-kings', title: 'Bandit Kings of Ancient China', aliases: ['Suikoden: Tenmei no Chikai'], cn: '水浒传：天命之誓', year: 1989, categories: ['strategy', 'simulation'], developer: 'Koei', publisher: 'Koei', players: 1 },
  { id: 'uncharted-waters', title: 'Uncharted Waters', aliases: ['Daikoukai Jidai'], cn: '大航海时代', year: 1991, categories: ['strategy', 'simulation'], developer: 'Koei', publisher: 'Koei', players: 1 },

  /* ------------------------------- 其他经典 -------------------------------- */
  { id: 'prince-of-persia', title: 'Prince of Persia', aliases: [], cn: '波斯王子', year: 1992, categories: ['platformer', 'action'], developer: null, publisher: null, players: 1 },
  { id: 'paperboy', title: 'Paperboy', aliases: [], cn: '送报童', year: 1988, categories: ['action'], developer: null, publisher: 'Mindscape', players: 1 },
  { id: 'micro-machines', title: 'Micro Machines', aliases: [], cn: null, year: 1991, categories: ['racing'], developer: 'Codemasters', publisher: 'Camerica', players: 2 },
  { id: 'battle-of-olympus', title: 'The Battle of Olympus', aliases: [], cn: null, year: 1988, categories: ['adventure', 'action'], developer: null, publisher: 'Broderbund', players: 1 },
  { id: 'tiger-heli', title: 'Tiger-Heli', aliases: ['Tiger Heli'], cn: null, year: 1987, categories: ['shooter'], developer: 'Toaplan', publisher: null, players: 1 },
  { id: 'snow-bros', title: 'Snow Bros.', aliases: ['Snow Brothers'], cn: '雪人兄弟', year: 1991, categories: ['platformer', 'action'], developer: 'Toaplan', publisher: null, players: 2 },
  { id: 'panic-restaurant', title: 'Panic Restaurant', aliases: ['Wanpaku Kokkun no Gourmet World'], cn: null, year: 1992, categories: ['platformer'], developer: null, publisher: 'Taito', players: 1 },
  { id: 'recca', title: "Summer Carnival '92: Recca", aliases: ['Recca'], cn: null, year: 1992, categories: ['shooter'], developer: 'KID', publisher: 'Naxat Soft', players: 1 },
  { id: 'ys', title: 'Ys', aliases: ['Ys: Ancient Ys Vanished'], cn: '伊苏', year: 1988, categories: ['rpg', 'action'], developer: 'Nihon Falcom', publisher: 'Victor', players: 1 },
  { id: 'deadly-towers', title: 'Deadly Towers', aliases: ['Mashou'], cn: null, year: 1986, categories: ['action', 'adventure'], developer: null, publisher: null, players: 1 },
  { id: 'ganso-saiyuuki', title: 'Ganso Saiyuuki: Super Monkey Dai Bouken', aliases: ['Super Monkey Adventure'], cn: '西游记', year: 1986, categories: ['adventure', 'rpg'], developer: null, publisher: 'Vap', players: 1 },
  { id: 'tetris-tengen', title: 'Tetris (Tengen)', aliases: ['Tengen Tetris'], cn: '俄罗斯方块（Tengen 版）', year: 1989, categories: ['puzzle'], developer: 'Tengen', publisher: 'Tengen', players: 2 },
  { id: 'ms-pac-man', title: 'Ms. Pac-Man', aliases: ['Ms Pacman'], cn: '吃豆小姐', year: 1990, categories: ['action', 'puzzle'], developer: null, publisher: null, players: 2 },
  { id: 'karateka', title: 'Karateka', aliases: [], cn: null, year: 1985, categories: ['fighting', 'action'], developer: null, publisher: null, players: 1 },
  { id: 'skate-or-die', title: 'Skate or Die!', aliases: ['Skate or Die'], cn: null, year: 1988, categories: ['sports'], developer: null, publisher: 'Electronic Arts', players: 2 },
  { id: 'kirby-pinball', title: "Kirby's Pinball Land", aliases: [], cn: null, year: null, categories: ['action'], developer: null, publisher: null, players: 1 },
  { id: 'the-goonies', title: 'The Goonies', aliases: ['Goonies'], cn: '七宝奇谋', year: 1986, categories: ['platformer', 'action'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'salamander-fds', title: 'Salamander', aliases: ['Lifeforce'], cn: '沙罗曼蛇', year: 1987, categories: ['shooter'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'exed-exes', title: 'Exed Exes', aliases: ['Savage Bees'], cn: null, year: 1985, categories: ['shooter'], developer: 'Capcom', publisher: 'Capcom', players: 2 },
  { id: 'son-son', title: 'SonSon', aliases: ['Son Son'], cn: null, year: 1986, categories: ['platformer', 'shooter'], developer: 'Capcom', publisher: 'Capcom', players: 2 },
  { id: 'higemaru', title: 'Pirate Ship Higemaru', aliases: ['Kaizoku-sen Higemaru', 'Higemaru'], cn: null, year: 1986, categories: ['action', 'puzzle'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'front-line', title: 'Front Line', aliases: [], cn: null, year: 1985, categories: ['shooter', 'action'], developer: 'Taito', publisher: 'Taito', players: 2 },
  { id: 'chack-n-pop', title: "Chack'n Pop", aliases: ['Chackn Pop'], cn: null, year: 1985, categories: ['puzzle', 'platformer'], developer: 'Taito', publisher: 'Taito', players: 1 },
  { id: 'seicross', title: 'Seicross', aliases: ['Sector Zone'], cn: null, year: 1984, categories: ['racing', 'shooter'], developer: null, publisher: 'Nichibutsu', players: 1 },
  { id: 'mario-bros-classic', title: 'Mario Bros. Classic Series', aliases: [], cn: null, year: null, categories: ['platformer'], developer: null, publisher: 'Nintendo', players: 2 },
  { id: 'tennis-family', title: 'Family Tennis', aliases: [], cn: null, year: 1987, categories: ['sports'], developer: 'Namco', publisher: 'Namco', players: 2 },
  { id: 'kid-kool', title: 'Kid Kool and the Quest for the Seven Wonder Herbs', aliases: ['Kid Kool'], cn: null, year: 1988, categories: ['platformer'], developer: null, publisher: 'Vic Tokai', players: 1 },
  { id: 'clash-at-demonhead', title: 'Clash at Demonhead', aliases: [], cn: null, year: 1989, categories: ['platformer', 'adventure'], developer: null, publisher: 'Vic Tokai', players: 1 },
  { id: 'golgo-13', title: 'Golgo 13: Top Secret Episode', aliases: ['Golgo 13'], cn: '骷髅13', year: 1988, categories: ['action', 'shooter'], developer: null, publisher: 'Vic Tokai', players: 1 },
  { id: 'the-mafat-conspiracy', title: 'The Mafat Conspiracy', aliases: ['Golgo 13 2'], cn: null, year: 1990, categories: ['action', 'shooter'], developer: null, publisher: 'Vic Tokai', players: 1 },
  { id: 'terra-cresta', title: 'Terra Cresta', aliases: [], cn: null, year: 1986, categories: ['shooter'], developer: null, publisher: 'Nichibutsu', players: 2 },
  { id: 'moon-crystal', title: 'Moon Crystal', aliases: [], cn: null, year: 1992, categories: ['platformer', 'action'], developer: null, publisher: 'Hect', players: 1 },
  { id: 'over-horizon', title: 'Over Horizon', aliases: [], cn: null, year: 1991, categories: ['shooter'], developer: null, publisher: null, players: 1 },
  { id: 'crisis-force-alt', title: 'Cosmo Police Galivan', aliases: ['Galivan'], cn: null, year: 1988, categories: ['action', 'platformer'], developer: null, publisher: 'Nichibutsu', players: 1 },
  { id: 'time-zone', title: 'Time Zone', aliases: [], cn: null, year: null, categories: ['other'], developer: null, publisher: null, players: 1 },
  { id: 'earthbound-zero', title: 'EarthBound Beginnings', aliases: ['Mother 1'], cn: '地球冒险', year: 1989, categories: ['rpg'], developer: 'Ape', publisher: 'Nintendo', players: 1 },
  { id: 'zoda-revenge', title: "Zoda's Revenge: StarTropics II", aliases: ['StarTropics II'], cn: null, year: 1994, categories: ['adventure', 'action'], developer: 'Nintendo', publisher: 'Nintendo', players: 1 },
  { id: 'gyruss', title: 'Gyruss', aliases: [], cn: null, year: 1988, categories: ['shooter'], developer: 'Konami', publisher: null, players: 2 },
  { id: 'skykid-deluxe', title: 'Sky Destroyer', aliases: [], cn: null, year: 1985, categories: ['shooter'], developer: 'Taito', publisher: 'Taito', players: 1 },
  { id: 'hyper-sports', title: 'Hyper Sports', aliases: [], cn: null, year: 1985, categories: ['sports'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'formation-z', title: 'Formation Z', aliases: [], cn: null, year: 1985, categories: ['shooter'], developer: 'Jaleco', publisher: 'Jaleco', players: 1 },
  { id: 'thexder', title: 'Thexder', aliases: [], cn: null, year: 1985, categories: ['shooter', 'action'], developer: 'Game Arts', publisher: null, players: 1 },
  { id: 'valkyrie-no-bouken', title: 'Valkyrie no Bouken: Toki no Kagi Densetsu', aliases: ['Valkyrie no Bouken'], cn: null, year: 1986, categories: ['action', 'rpg'], developer: 'Namco', publisher: 'Namco', players: 1 },
  { id: 'legend-of-valkyrie', title: 'Babel no Tou', aliases: ['Tower of Babel'], cn: '巴别塔', year: 1986, categories: ['puzzle'], developer: 'Namco', publisher: 'Namco', players: 1 },
  { id: 'metro-cross', title: 'Metro-Cross', aliases: ['Metro Cross'], cn: null, year: 1986, categories: ['action'], developer: 'Namco', publisher: 'Namco', players: 1 },
  { id: 'battle-formula', title: 'Battle Formula', aliases: ['Super Spy Hunter'], cn: null, year: 1991, categories: ['racing', 'shooter'], developer: 'Sunsoft', publisher: 'Sunsoft', players: 1 },
  { id: 'spy-hunter', title: 'Spy Hunter', aliases: [], cn: null, year: 1987, categories: ['racing', 'shooter'], developer: null, publisher: 'Sunsoft', players: 1 },
  { id: 'after-burner', title: 'After Burner', aliases: [], cn: null, year: 1989, categories: ['shooter', 'simulation'], developer: null, publisher: 'Sunsoft', players: 1 },
  { id: 'wizardry', title: 'Wizardry: Proving Grounds of the Mad Overlord', aliases: ['Wizardry'], cn: '巫术', year: 1987, categories: ['rpg'], developer: null, publisher: 'ASCII', players: 1 },
  { id: 'ultima-exodus', title: 'Ultima: Exodus', aliases: ['Ultima III'], cn: '创世纪', year: 1987, categories: ['rpg'], developer: null, publisher: 'FCI', players: 1 },
  { id: 'tetris-2', title: 'Tetris 2', aliases: [], cn: '俄罗斯方块2', year: 1993, categories: ['puzzle'], developer: null, publisher: 'Nintendo', players: 2 },
  { id: 'palamedes', title: 'Palamedes', aliases: [], cn: null, year: 1990, categories: ['puzzle'], developer: null, publisher: 'Hot-B', players: 2 },
  { id: 'puzznic', title: 'Puzznic', aliases: [], cn: null, year: 1990, categories: ['puzzle'], developer: 'Taito', publisher: 'Taito', players: 1 },
  { id: 'pipe-dream', title: 'Pipe Dream', aliases: ['Pipe Mania'], cn: '水管工人', year: 1990, categories: ['puzzle'], developer: null, publisher: null, players: 2 },
  { id: 'qix', title: 'Qix', aliases: [], cn: '圈圈叉叉', year: 1991, categories: ['puzzle'], developer: 'Taito', publisher: 'Taito', players: 2 },
  { id: 'hatris', title: 'Hatris', aliases: [], cn: null, year: 1990, categories: ['puzzle'], developer: null, publisher: 'Bullet-Proof Software', players: 2 },
  { id: 'yoshis-egg', title: 'Yoshi no Tamago', aliases: [], cn: '耀西的蛋', year: 1991, categories: ['puzzle'], developer: null, publisher: 'Nintendo', players: 2 },
  { id: 'lolo-eggerland', title: 'Eggerland: Meikyuu no Fukkatsu', aliases: ['Eggerland'], cn: null, year: 1988, categories: ['puzzle'], developer: 'HAL Laboratory', publisher: 'HAL Laboratory', players: 1 },
  { id: 'joust', title: 'Joust', aliases: [], cn: null, year: 1988, categories: ['action'], developer: null, publisher: null, players: 2 },
  { id: 'defender-ii', title: 'Defender II', aliases: ['Stargate'], cn: null, year: 1988, categories: ['shooter'], developer: null, publisher: null, players: 2 },
  { id: 'gauntlet', title: 'Gauntlet', aliases: [], cn: null, year: 1987, categories: ['action', 'rpg'], developer: null, publisher: 'Tengen', players: 2 },
  { id: 'gauntlet-2', title: 'Gauntlet II', aliases: [], cn: null, year: 1990, categories: ['action', 'rpg'], developer: null, publisher: 'Mindscape', players: 4 },
  { id: 'rbi-baseball', title: 'R.B.I. Baseball', aliases: ['RBI Baseball'], cn: null, year: 1987, categories: ['sports'], developer: null, publisher: 'Tengen', players: 2 },
  { id: 'super-sprint', title: 'Super Sprint', aliases: [], cn: null, year: 1989, categories: ['racing'], developer: null, publisher: 'Tengen', players: 2 },
  { id: 'road-runner', title: 'Road Runner', aliases: [], cn: null, year: 1989, categories: ['action'], developer: null, publisher: 'Tengen', players: 1 },
  { id: 'klax', title: 'Klax', aliases: [], cn: null, year: 1990, categories: ['puzzle'], developer: null, publisher: 'Tengen', players: 1 },
  { id: 'toobin', title: "Toobin'", aliases: ['Toobin'], cn: null, year: 1989, categories: ['action'], developer: null, publisher: 'Tengen', players: 2 },
  { id: 'vindicators', title: 'Vindicators', aliases: [], cn: null, year: 1988, categories: ['shooter'], developer: null, publisher: 'Tengen', players: 2 },
  { id: 'kabuki-quantum-fighter', title: 'Kabuki: Quantum Fighter', aliases: [], cn: null, year: 1990, categories: ['action', 'platformer'], developer: null, publisher: 'HAL Laboratory', players: 1 },
  { id: 'isolated-warrior', title: 'Isolated Warrior', aliases: ['Max Warrior'], cn: null, year: 1991, categories: ['shooter'], developer: null, publisher: null, players: 1 },
  { id: 'rad-gravity', title: 'The Adventures of Rad Gravity', aliases: ['Rad Gravity'], cn: null, year: 1990, categories: ['platformer', 'adventure'], developer: null, publisher: 'Activision', players: 1 },
  { id: 'river-city-ransom-jp', title: 'Downtown Nekketsu Monogatari', aliases: ['Nekketsu Monogatari'], cn: '热血物语', year: 1989, categories: ['action', 'rpg'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 2 },
  { id: 'super-mario-bros-duckhunt', title: 'Super Mario Bros. / Duck Hunt', aliases: [], cn: null, year: 1988, categories: ['platformer', 'shooter'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'castle-excellent', title: 'Castlequest', aliases: ['Castle Excellent'], cn: null, year: 1989, categories: ['puzzle', 'platformer'], developer: null, publisher: null, players: 1 },
  { id: 'the-magic-of-scheherazade', title: 'The Magic of Scheherazade', aliases: ['Arabian Dream Scheherazade'], cn: '天方夜谭', year: 1987, categories: ['rpg', 'action'], developer: null, publisher: 'Culture Brain', players: 1 },
  { id: 'god-slayer', title: 'God Slayer: Haruka Tenkuu no Sonata', aliases: ['God Slayer'], cn: null, year: 1990, categories: ['rpg', 'action'], developer: 'SNK', publisher: 'SNK', players: 1 },
  { id: 'digital-devil-story', title: 'Digital Devil Story: Megami Tensei', aliases: ['Megami Tensei'], cn: '女神转生', year: 1987, categories: ['rpg'], developer: 'Atlus', publisher: 'Namco', players: 1 },
  { id: 'megami-tensei-2', title: 'Digital Devil Story: Megami Tensei II', aliases: ['Megami Tensei II'], cn: '女神转生2', year: 1990, categories: ['rpg'], developer: 'Atlus', publisher: 'Namco', players: 1 },
  { id: 'sweet-home-alt', title: 'Sweet Home (Famicom)', aliases: [], cn: '甜蜜之家', year: 1989, categories: ['rpg', 'adventure'], developer: 'Capcom', publisher: 'Capcom', players: 1 },
  { id: 'akumajou-special', title: 'Akumajou Special: Boku Dracula-kun', aliases: ['Kid Dracula'], cn: '小恶魔城', year: 1990, categories: ['platformer'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'tiny-toon-2', title: 'Tiny Toon Adventures 2: Trouble in Wackyland', aliases: ['Tiny Toon 2'], cn: '淘气小兵兵2', year: 1992, categories: ['platformer'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'yie-ar-kung-fu-2', title: 'Yie Ar Kung-Fu 2', aliases: [], cn: null, year: 1985, categories: ['fighting'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'nekketsu-soccer-league', title: 'Kunio-kun no Nekketsu Soccer League', aliases: ['Nekketsu Soccer League'], cn: '热血足球联赛', year: 1993, categories: ['sports'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 4 },
  { id: 'kunio-kun-dodgeball-2', title: 'Nekketsu Koukou Dodgeball-bu: Soccer Hen', aliases: [], cn: '热血足球', year: 1990, categories: ['sports'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 4 },
  { id: 'downtown-special', title: 'Downtown Special: Kunio-kun no Jidaigeki Dayo Zenin Shuugou!', aliases: ['Downtown Special'], cn: '热血时代剧', year: 1991, categories: ['action', 'rpg'], developer: 'Technos Japan', publisher: 'Technos Japan', players: 2 },
  { id: 'sd-hero-soukessen', title: 'SD Hero Soukessen: Taose! Aku no Gundan', aliases: ['SD Hero'], cn: null, year: 1990, categories: ['action', 'fighting'], developer: null, publisher: 'Banpresto', players: 2 },
  { id: 'ultraman-club', title: 'Ultraman Club: Chikyuu Dakkan Sakusen', aliases: ['Ultraman Club'], cn: '奥特曼俱乐部', year: 1990, categories: ['rpg'], developer: null, publisher: 'Bandai', players: 1 },
  { id: 'kamen-rider-club', title: 'Kamen Rider Club: Gekitotsu Shocker Land', aliases: ['Kamen Rider Club'], cn: '假面骑士俱乐部', year: 1988, categories: ['rpg', 'action'], developer: null, publisher: 'Bandai', players: 1 },
  { id: 'gegege-no-kitarou-2', title: 'Gegege no Kitarou 2: Youkai Gundan no Chousen', aliases: ['Gegege no Kitarou 2'], cn: '鬼太郎2', year: 1987, categories: ['action', 'platformer'], developer: null, publisher: 'Bandai', players: 1 },
  { id: 'ninja-hattori-kun', title: 'Ninja Hattori-kun', aliases: ['Hattori-kun'], cn: '忍者哈特利', year: 1986, categories: ['platformer', 'action'], developer: null, publisher: 'Hudson Soft', players: 1 },
  { id: 'obake-no-q-taro', title: 'Obake no Q-Taro: Wanwan Panic', aliases: ['Obake no Q-Taro'], cn: '小鬼Q太郎', year: 1985, categories: ['platformer'], developer: null, publisher: 'Bandai', players: 1 },
  { id: 'chubby-cherub', title: 'Chubby Cherub', aliases: ['Obake no Q Taro'], cn: null, year: 1986, categories: ['platformer'], developer: null, publisher: 'Bandai', players: 1 },
  { id: 'ninja-kid', title: 'Ninja Kid', aliases: ['Ninja Jajamaru Kun'], cn: null, year: 1986, categories: ['platformer'], developer: 'Jaleco', publisher: 'Jaleco', players: 2 },
  { id: 'magmax', title: 'MagMax', aliases: [], cn: null, year: 1986, categories: ['shooter'], developer: null, publisher: 'Nichibutsu', players: 1 },
  { id: 'terra-force', title: 'Terra Force', aliases: [], cn: null, year: 1987, categories: ['shooter'], developer: null, publisher: 'Nichibutsu', players: 1 },
  { id: 'sqoon', title: 'Sqoon', aliases: [], cn: null, year: 1986, categories: ['shooter'], developer: null, publisher: 'Irem', players: 1 },
  { id: 'lot-lot', title: 'Lot Lot', aliases: [], cn: null, year: 1985, categories: ['puzzle'], developer: 'Irem', publisher: 'Irem', players: 1 },
  { id: 'kickle-cubicle', title: 'Kickle Cubicle', aliases: ['Meikyuu Jima'], cn: null, year: 1988, categories: ['puzzle'], developer: 'Irem', publisher: 'Irem', players: 1 },
  { id: 'the-battle-of-olympus-alt', title: 'Olympus no Tatakai', aliases: [], cn: null, year: 1988, categories: ['adventure', 'action'], developer: null, publisher: 'Imagineer', players: 1 },
  { id: 'moero-pro-yakyuu', title: 'Moero!! Pro Yakyuu', aliases: ['Bases Loaded'], cn: null, year: 1987, categories: ['sports'], developer: 'Jaleco', publisher: 'Jaleco', players: 2 },
  { id: 'shufflepuck-cafe', title: 'Shufflepuck Cafe', aliases: [], cn: null, year: null, categories: ['sports'], developer: null, publisher: null, players: 2 },
  { id: 'wario-woods-alt', title: 'Mario & Wario', aliases: [], cn: null, year: null, categories: ['puzzle'], developer: null, publisher: null, players: 1 },
  { id: 'jackal-alt', title: 'Tokushu Butai Jackal', aliases: [], cn: '赤色要塞', year: 1988, categories: ['shooter'], developer: 'Konami', publisher: 'Konami', players: 2 },
  { id: 'chuka-taisen', title: 'Chuka Taisen', aliases: ['Cloud Master'], cn: '中华大仙', year: 1989, categories: ['shooter'], developer: null, publisher: 'Taito', players: 1 },
  { id: 'wonder-boy', title: 'Wonder Boy', aliases: [], cn: '神奇小子', year: 1986, categories: ['platformer'], developer: 'Escape', publisher: null, players: 1 },
  { id: 'flappy', title: 'Flappy', aliases: [], cn: null, year: 1985, categories: ['puzzle'], developer: null, publisher: 'dB-SOFT', players: 1 },
  { id: 'door-door', title: 'Door Door', aliases: [], cn: null, year: 1985, categories: ['puzzle'], developer: 'Chunsoft', publisher: 'Enix', players: 1 },
  { id: 'portopia', title: 'The Portopia Serial Murder Case', aliases: ['Portopia Renzoku Satsujin Jiken'], cn: '港口连续杀人事件', year: 1985, categories: ['adventure'], developer: 'Chunsoft', publisher: 'Enix', players: 1 },
  { id: 'jesus', title: 'Jesus: Kyoufu no Bio Monster', aliases: ['Jesus'], cn: null, year: 1989, categories: ['adventure'], developer: null, publisher: 'King Records', players: 1 },
  { id: 'shadowgate', title: 'Shadowgate', aliases: [], cn: null, year: 1989, categories: ['adventure'], developer: null, publisher: 'Kemco', players: 1 },
  { id: 'deja-vu', title: 'Deja Vu', aliases: [], cn: null, year: 1990, categories: ['adventure'], developer: null, publisher: 'Kemco', players: 1 },
  { id: 'uninvited', title: 'Uninvited', aliases: [], cn: null, year: 1991, categories: ['adventure'], developer: null, publisher: 'Kemco', players: 1 },
  { id: 'mickey-mouse-3', title: 'Mickey Mouse III: Yume Fuusen', aliases: ['Kid Klown in Night Mayor World'], cn: null, year: 1992, categories: ['platformer'], developer: null, publisher: 'Kemco', players: 1 },
  { id: 'sky-shark', title: 'Sky Shark', aliases: ['Hishouzame'], cn: null, year: 1989, categories: ['shooter'], developer: 'Toaplan', publisher: null, players: 2 },
  { id: 'twin-cobra', title: 'Twin Cobra', aliases: ['Kyuukyoku Tiger'], cn: null, year: 1990, categories: ['shooter'], developer: 'Toaplan', publisher: null, players: 2 },
  { id: 'fire-shark', title: 'Fire Shark', aliases: ['Same! Same! Same!'], cn: null, year: null, categories: ['shooter'], developer: 'Toaplan', publisher: null, players: 2 },
  { id: 'zombie-nation', title: 'Zombie Nation', aliases: ['Abarenbou Tengu'], cn: null, year: 1990, categories: ['shooter'], developer: null, publisher: 'Meldac', players: 1 },
  { id: 'sansuu', title: 'Donkey Kong Jr. Math', aliases: ['DK Jr Math'], cn: '大金刚数学', year: 1983, categories: ['educational'], developer: 'Nintendo', publisher: 'Nintendo', players: 2 },
  { id: 'mario-teaches-typing', title: "Mario's Time Machine", aliases: [], cn: null, year: 1993, categories: ['educational'], developer: null, publisher: 'Mindscape', players: 1 },
  { id: 'sesame-street-123', title: 'Sesame Street 1-2-3', aliases: [], cn: null, year: 1989, categories: ['educational'], developer: null, publisher: 'Hi Tech Expressions', players: 1 },
  { id: 'castlevania-kid-dracula', title: 'Kid Dracula', aliases: ['Boku Dracula-kun'], cn: null, year: 1990, categories: ['platformer'], developer: 'Konami', publisher: 'Konami', players: 1 },
  { id: 'gradius-life-force-fds', title: 'Gradius (FDS)', aliases: [], cn: '宇宙巡航机', year: 1986, categories: ['shooter'], developer: 'Konami', publisher: 'Konami', players: 2 },
]

/** 便于按 id 反查 */
export function findTitleById(id: string): TitleEntry | undefined {
  return NES_TITLES.find((entry) => entry.id === id)
}
